### ISSUE TITLE
Help with the input files

### ISSUE THREAD

**Issue by carioka88** [jydu/comap#1]
Hello, 

I would like to use CoMap to detect co-evolution.
But I am having some troubles executing comap.
What kind of input files does the program allow?
- .fasta .phy ?

I see that there are some examples with some values for data loading like:
  input.sequence.format = Mase
Does it mean Fasta format? And for the phylip format?
Also, does the MSA allow gaps or unknown values?

Does the tree need to be rooted or unrooted?

Thank you in advance!

**Comment by jydu** [comment]
Hi,

CoMap can read fasta, phylip (interleaved, extended), clustal and mase alignments.

Mase means Mase format ;) If you need a Fasta format, then use input.sequence.format = Fasta
Gap and unresolved characters are allowed and can be filtered (for instance keeping only sites with a maximum of x% gaps).

Tree should be unrooted if a homogeneous model is used, rooted if otherwise. The default and most common usage is with a homogeneous model.

Hope this helps,

Julien.

**Comment by carioka88** [comment]
It helped!

Also, I had more information after each specie name, I removed the extra information, leaving only the specie name (>SPECIE_NAME) and it worked.

Thanks!

**Comment by carioka88** [comment]
It helped!

Also, I had more information after each specie name in the fasta file.
I removed the extra information, leaving only the specie name (>SPECIE_NAME) and it worked.

Thanks!
