### ISSUE TITLE
Help debugging CoMap error

### ISSUE THREAD

**Issue by carioka88** [jydu/comap#3]
Hello,

I am running CoMap, for a MSA of 3700 species with a length of 625.
I was getting this error:

```
ERROR!!! !!! Unexpected initial likelihood == 0.

ERROR!!! !!! Site-specific likelihood have been written in file DEBUG_likelihoods.txt .

ERROR!!! !!! 0 values (inf in log) may be due to computer overflow, particularily if datasets are big (>~500 sequences).

ERROR!!! !!! You may want to try input.sequence.remove_saturated_sites = yes to ignore positions with likelihood 0.
```

So I set the value **input.sequence.remove_saturated_sites = yes** in the configuration file.

But now, I am getting this error:

```
-*- Perform pairwise analysis -*-

Number of sub-distributions............: 10

Nb of simulations to perform...........: 100000

[                                      ]   0%terminate called after throwing an instance of 'bpp::Exception'

  what():  Unexpected error!

Aborted
```

Any idea what parameters should I check or how I could debug this error?

Thank you in advance!

**Comment by jydu** [comment]
Hi,

the problem is most likely due to the large number of sequences in your dataset, creating numerical underflow. CoMap currently cannot handle more than ~400 protein sequences (a bit more for nucleotide sequences). In most cases, however, many sequences in large datasets are very similar and do not carry any coevolution signal, but slow down the calculations considerably. It is, therefore, a good idea to reduce the dataset before analysis. My recommendation is to first remove some sequences to minimize the amount of missing data, and then remove sequences based on the phylogeny to remove any redundancy. You may be interested in my package "physamp", also on GitHub, in order to perform these steps. Alternatively, you can conduct coevolution analyses on subgroups separately.

Hope this helps,

Julien.
